### ISSUE TITLE
All or nothing

### ISSUE THREAD

**Issue by alexmcmillan** [magalhas/backbone-react-component#36]
Apparently you have to use the mixin on the absolute global root component or it doesn't work at all... 

I'm having trouble rendering 3 components (all using the mixin) inside a common (React) container (*not* using the mixin).

I think it may be to do with the "Wrapper" only starting listeners on a root node, when I'm essentially trying to create 3 "root nodes" - meaning they all have a `component._owner`, and nothing ever satisfies the conditional to trigger the calls to `this.startModelListeners()` and `this.startCollectionListeners()`

Any ideas?

**Comment by alexmcmillan** [comment]
> Hi, it doesn't make sense to have components using the mixin without having a root component using it as well.

My root React component is a document editor `<Editor />`.  There is no "data model" associated with the editor itself - it just renders a bunch of UI dom, and listens to a Controller for when the document data is available.

While waiting, it renders a `<Toolbar />`, a `<Sidebar />`, menus, and a "please wait" prompt.  When the data is available, it renders a `<Document model={documentModel} />` in place of the "please wait".

How does this not make sense?  And how can I achieve the same while satisfying the requirement that the root component be attached to a data model?

**Comment by magalhas** [comment]
Hi @alexmcmillan . How are you notifying your `<Editor />` that data is available in order to render `<Document model={documentModel} />`?

**Comment by alexmcmillan** [comment]
The `Editor` component is first created by an 'ApplicationController' which itself instructs aalso fires an ajax request for the data.  When it arrives, the ApplicationController

**Comment by magalhas** [comment]
So can I assume that the controller calls setProps on the Editor instance, right?

Cumprimentos,
José Magalhães

**Comment by alexmcmillan** [comment]
I think this does essentially the same thing, but here's a simplified example of what I'm doing:

    var docModel = null;

    renderEditor: function () {
        React.renderComponent(<Editor documentModel={docModel} />, $('#container')[0]);
    }

    dataController.on('ready', function () {
        docModel = this.getDocumentModel();
        renderEditor();
    }

    renderEditor();

**Comment by magalhas** [comment]
So in fact there's a "data model" associated with your `Editor`, right?

**Comment by alexmcmillan** [comment]
Precisely.  That's the problem.

**Comment by magalhas** [comment]
How do you pass the data from the `<Editor />` into it child components? Your use case as described above should be working fine.

**Comment by alexmcmillan** [comment]
I'm passing the `documentModel` as a prop to the editor, but not as its `model` prop.  The `Editor`, if it receives a `documentModel` property, renders a `<Document model={this.props.documentModel} />`.

I still don't see how this is wrong, or even an edge case.  Sure, I could pass the `documentModel` as the `model` prop to both the `Document` AND the `Editor` but it just doesn't make sense.

Please explain what's wrong with my example, and why it "doesn't make sense to have components using the mixin without having a root component using it as well".  I appreciate your help

**Comment by magalhas** [comment]
Because the nature of the mixin uses `setProps`. There are some discuss over the repo over changing `setProps` to `setState`, if that happens then there won't be this limitation.

**Comment by alexmcmillan** [comment]
Ok cool.  Perhaps you could use this as an example of the mixin not necessarily being used for a complete application.  Thanks for your help, i'll keep an eye on future updates :-)

**Comment by magalhas** [comment]
@alexmcmillan check out the master already include all #55 changes so this is no longer an issue, feel free to try it out and let me know if you have any feedback

**Comment by alexmcmillan** [comment]
@magalhas nice work :)  thanks for taking the time to do this.  I made my own (albeit simple) `BackboneReactComponent` that uses `state` so that I could continue with my project, but I will replace it with yours shortly, see how it goes and let you know.

**Comment by magalhas** [comment]
@alexmcmillan I've already released v0.8.0-beta.1 so feel free to use it. As of now this shouldn't be reproducible anymore so I'm going to close it.
